server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./src/main/resources
    username: sa
    password: 1234
  jpa:
    show-sql: true